language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - npm i -g data-cli
script:
  - python process.py
  - python package.py
after_script:
  - data push datasets/bundesliga/
  - data push datasets/la-liga/
  - data push datasets/ligue-1/
  - data push datasets/premier-league/
  - data push datasets/serie-a/
